language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - py.test
  - python -OO -m py.test tests/test_enum.py
